#!/bin/bash

wp --allow-root post create --post_type=page --post_title="Como Comprar" --post_status=publish --post_content="Comprar em nossa loja é simples, rápido e seguro! Siga estes passos:\n\n1. Escolha seu produto: Navegue pelas categorias ou use a busca.\n2. Adicione ao carrinho: Clique em “Adicionar ao Carrinho”.\n3. Finalize a compra: Acesse seu carrinho e clique em “Finalizar Compra”.\n4. Informe seus dados: Preencha o endereço de entrega e escolha o método de pagamento.\n5. Pronto! Após a confirmação, enviaremos seu pedido com rapidez e segurança.\n\nEm caso de dúvidas, consulte nossas Perguntas Frequentes ou entre em contato com nosso suporte."

wp --allow-root post create --post_type=page --post_title="Perfil de Cores" --post_status=publish --post_content="Para impressões com cores perfeitas, oferecemos perfis de cores otimizados para diferentes modelos de impressoras.\n\n- Baixe aqui seu perfil de cor: [Adicione aqui o link de download]\n- Como instalar: Consulte nosso tutorial ou solicite suporte gratuito para instalação do perfil.\n\nGaranta sempre a melhor qualidade nas suas impressões com nossos perfis de cor!"

wp --allow-root post create --post_type=page --post_title="Perguntas Frequentes" --post_status=publish --post_content="1. Os produtos são originais?\nOferecemos peças originais e compatíveis de alta qualidade, sempre especificadas no anúncio.\n\n2. Qual o prazo de envio?\nEnviamos para todo o Brasil em até 24h após confirmação do pagamento.\n\n3. Como faço para solicitar uma troca?\nVocê pode solicitar a troca em até 7 dias após o recebimento, seguindo nossa política abaixo.\n\n4. Vocês ajudam na instalação de peças?\nSim! Oferecemos suporte especializado por WhatsApp e e-mail.\n\n5. Como recebo o código de rastreio?\nApós a postagem, enviamos o código de rastreio por e-mail automaticamente.\n\nFicou com dúvidas? Fale conosco para atendimento personalizado!"

wp --allow-root post create --post_type=page --post_title="Políticas e Privacidade" --post_status=publish --post_content="Sua privacidade é nossa prioridade! Utilizamos seus dados apenas para processar pedidos e melhorar sua experiência em nosso site.\n\n- Não compartilhamos seus dados com terceiros.\n- Todas as transações são protegidas por criptografia.\n- Você pode solicitar exclusão dos seus dados a qualquer momento.\n\nLeia atentamente nossa política completa nesta página. Qualquer dúvida, entre em contato com nossa equipe."

wp --allow-root post create --post_type=page --post_title="Regulamento das Promoções" --post_status=publish --post_content="Nossas promoções são válidas enquanto durarem os estoques.\n- Cupons de desconto não são cumulativos.\n- O período de validade de cada promoção está informado na página do produto.\n- Reservamo-nos o direito de alterar ou cancelar promoções a qualquer momento, sem aviso prévio.\n\nFique ligado em nossas redes sociais para não perder nenhuma oferta!"

wp --allow-root post create --post_type=page --post_title="Trocas e Devoluções" --post_status=publish --post_content="Nossa política de trocas e devoluções segue o Código de Defesa do Consumidor:\n\n- Solicite a troca ou devolução em até 7 dias após o recebimento.\n- O produto deve estar sem uso e em embalagem original.\n- Para iniciar o processo, envie um e-mail ou WhatsApp com o número do pedido e o motivo.\n\nNossa equipe está pronta para te ajudar em todas as etapas do processo!"
